music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands 
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true 
end

music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in_user!(user)
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band
      render :show
    else
      redirect_to bands_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    if @band
      @band.destroy
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :destroy
    end
  end

  private
    def band_params
      params.require(:band).permit(:name)
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:users][:email], params[:users][:password])
    if user.nil?
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user.id)
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      render :new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        log_in_user!(@user)
        redirect_to user_url(@user.id)
      else
        flash.now[:errors] = @user.errors.full_messages
        render :new
      end
    end

    def show
      @user = User.find_by(id: params[:id])
      render :show
    end

    private

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/bands/edit.html.erb
<h2>Edit Band!</h2>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name">Name</label>
      <input type="text"
        name="band[name]"
        id="name"
        value="<%= @band.name %>">
      <br>

  <div1 class="submit">
    <input type="submit" value="submit">
  </div1>
</form>

music_app/app/views/bands/index.html.erb
<h2>Bands</h2>
  <%= button_to "Create Band", new_band_url, method: :get %>

<ul class="band"><% @bands.each do |band|  %>
  <li><%= band.name %><a href= "<%= band_url(band.id) %>">More Info</a></li>
<% end %> </ul>

music_app/app/views/bands/new.html.erb
<h2>New Band!</h2>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= bands_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name">Name</label>
      <input type="text"
        name="band[name]"
        id="name"
      <br>

  <div1 class="submit">
    <input type="submit" value="submit">
  </div1>
</form>

music_app/app/views/bands/show.html.erb
<h2><%= @band.name %></h2>
  <div3>
    <li><%= button_to "Edit", edit_band_url(@band), method: :get %></li>
    <li><%= button_to "Delete", band_url(@band), method: :delete %></li>
  </div3>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

<title>Music App</title>
  <header>
  <h1>Music App</h1>
    <%= button_to "Home", bands_url, method: :get %>
  <div>
  <% if logged_in? %>
    <li><%= "Logged in as: #{current_user.email}" %></li>
    <%= button_to "Log Out", session_url, method: :delete %>
  <% else %>
    <li><%= button_to "Log In", new_session_url, method: :get %></li>
    <li><%= button_to "Sign Up", new_user_url, method: :get %></li>

  <% end  %>
  </div>

  </header>

  <body>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h2>New User</h2>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>


<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="email">Email</label>
      <input type="text"
        name="user[email]"
        id="email"
      <br>

  <label for="password">Password</label>
      <input type="text"
        name="user[password]"
        id="password"
      <br>
  <div1 class="submit">
  <input type="submit" value="submit">
  </div1>
</form>

music_app/app/views/users/show.html.erb
<%= "Welcome! Your email is" %>
<%= @user.email %>